-- Schema para testes com H2
-- Sem CHECK constraints de enum (incompatível com H2 2.2.x + Hibernate 7)

DROP TABLE IF EXISTS tarefas;

CREATE TABLE tarefas (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descricao  VARCHAR(255) NOT NULL,
    status     VARCHAR(10)  NOT NULL,
    observacoes TEXT,
    data_criacao     TIMESTAMP NOT NULL,
    data_atualizacao TIMESTAMP NOT NULL
);
